// Refs: WP-020 FR-DOC-003 FR-DX-002
import * as Components from "@conductor-by-89soone/react";
import generated from "./generated/component-meta.json";
import { Component, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { CopyCode } from "./guides";

export interface ComponentMeta { readonly name: string; readonly propsTypeName: string; readonly props: readonly { readonly name: string; readonly required: boolean; readonly type: string }[]; }
export const componentMeta = generated as readonly ComponentMeta[];

class PreviewBoundary extends Component<{ readonly children: ReactNode }, { readonly failed: boolean }> {
  override state = { failed: false };
  static getDerivedStateFromError(): { failed: boolean } { return { failed: true }; }
  override componentDidCatch(): void {}
  override render(): ReactNode { return this.state.failed ? <Components.Banner tone="danger">This preview could not render.</Components.Banner> : this.props.children; }
}

export function ComponentPreview({ compact = false, forceError = false, name }: { readonly compact?: boolean; readonly forceError?: boolean; readonly name: string }) {
  if (forceError) throw new Error(`Forced ${name} preview failure`);
  switch (name) {
    case "Button": { if (compact) return <Components.Button tone="accent">Deploy release</Components.Button>; const labels = { neutral: "Continue", accent: "Deploy", danger: "Delete" } as const; return <div className="docs-button-matrix">{(["primary", "secondary", "ghost"] as const).map((variant) => <div className="docs-button-matrix__row" key={variant}><span className="docs-preview-meta">{variant}</span><div className="docs-preview-row">{(["neutral", "accent", "danger"] as const).map((tone) => <Components.Button key={`${variant}-${tone}`} variant={variant} tone={tone}>{labels[tone]}</Components.Button>)}</div></div>)}</div>; }
    case "IconButton": return <Components.IconButton aria-label="Open command palette" icon="⌘" />;
    case "Card": return <Components.Card><div className="docs-preview-card"><span className="docs-preview-meta">Operational status</span><strong>All systems nominal</strong><span className="cdt-muted">Last checked 2 minutes ago</span></div></Components.Card>;
    case "CardGrid": return <Components.CardGrid><Components.Card><div className="docs-preview-card"><span className="docs-preview-meta">Requests</span><strong className="docs-preview-value">24.8k</strong></div></Components.Card><Components.Card><div className="docs-preview-card"><span className="docs-preview-meta">Success rate</span><strong className="docs-preview-value">99.98%</strong></div></Components.Card></Components.CardGrid>;
    case "Panel": return <Components.Panel><div className="docs-preview-card"><span className="docs-preview-meta">Environment</span><strong>Production</strong><span className="cdt-muted">Region ap-northeast-2</span></div></Components.Panel>;
    case "Badge": return <div className="docs-preview-row">{(["neutral", "accent", "info", "success", "warning", "danger"] as const).map((tone) => <Components.Badge key={tone} tone={tone}>{tone}</Components.Badge>)}</div>;
    case "StatusBadge": return <Components.StatusBadge status="running" icon="●" label="Deployment running" />;
    case "SeverityTag": return <Components.SeverityTag severity="destructive" icon="!" label="Destructive" />;
    case "Table": return <Components.Table caption="Recent deployments"><Components.Table.Head><Components.Table.Row><Components.Table.HeaderCell>Service</Components.Table.HeaderCell><Components.Table.HeaderCell>Status</Components.Table.HeaderCell><Components.Table.HeaderCell>Duration</Components.Table.HeaderCell></Components.Table.Row></Components.Table.Head><Components.Table.Body><Components.Table.Row><Components.Table.Cell><strong>web-console</strong></Components.Table.Cell><Components.Table.Cell><Components.StatusBadge status="success" icon="✓" label="Healthy" /></Components.Table.Cell><Components.Table.Cell numeric>42s</Components.Table.Cell></Components.Table.Row><Components.Table.Row><Components.Table.Cell><strong>event-worker</strong></Components.Table.Cell><Components.Table.Cell><Components.StatusBadge status="running" icon="●" label="Running" /></Components.Table.Cell><Components.Table.Cell numeric>18s</Components.Table.Cell></Components.Table.Row></Components.Table.Body></Components.Table>;
    case "Timeline": return <Components.Timeline><Components.Timeline.Step>Validated</Components.Timeline.Step><Components.Timeline.Step selected>Deploying to production</Components.Timeline.Step><Components.Timeline.Step>Traffic migration</Components.Timeline.Step></Components.Timeline>;
    case "CodeBlock": return <Components.CodeBlock language="tsx" code="&lt;Button&gt;Save&lt;/Button&gt;" />;
    case "Kbd": return <Components.Kbd>Esc</Components.Kbd>;
    case "Dialog": return <Components.Dialog.Root><Components.Dialog.Trigger>Open dialog</Components.Dialog.Trigger><Components.Dialog.Content><Components.Dialog.Title>Promote to production?</Components.Dialog.Title><Components.Dialog.Description>The release passed every required check. This action will make it available to all users.</Components.Dialog.Description><div className="docs-dialog-actions"><Components.Dialog.Close asChild><Components.Button variant="ghost">Cancel</Components.Button></Components.Dialog.Close><Components.Dialog.Close asChild><Components.Button variant="primary">Promote release</Components.Button></Components.Dialog.Close></div></Components.Dialog.Content></Components.Dialog.Root>;
    case "Drawer": return <Components.Drawer.Root><Components.Drawer.Trigger>Open drawer</Components.Drawer.Trigger><Components.Drawer.Content><Components.Drawer.Title>Drawer</Components.Drawer.Title></Components.Drawer.Content></Components.Drawer.Root>;
    case "Tooltip": return <Components.Tooltip.Provider><Components.Tooltip.Root><Components.Tooltip.Trigger>Tooltip trigger</Components.Tooltip.Trigger><Components.Tooltip.Content>Tooltip</Components.Tooltip.Content></Components.Tooltip.Root></Components.Tooltip.Provider>;
    case "DropdownMenu": return <Components.DropdownMenu.Root><Components.DropdownMenu.Trigger>Menu trigger</Components.DropdownMenu.Trigger><Components.DropdownMenu.Content><Components.DropdownMenu.Item>Item</Components.DropdownMenu.Item></Components.DropdownMenu.Content></Components.DropdownMenu.Root>;
    case "Field": return <Components.Field label="Workspace name" description="Shown to everyone in this workspace."><Components.TextField defaultValue="Conductor" /></Components.Field>;
    case "TextField": return <Components.Field label="Search components" description="Filter by component name or category."><Components.TextField defaultValue="Button" /></Components.Field>;
    case "TextArea": return <Components.Field label="Release notes" description="Summarize the user-visible changes in this release."><Components.TextArea defaultValue="Improved component clarity and visual hierarchy." /></Components.Field>;
    case "Select": return <Components.Field label="Environment" description="Choose where this release will be deployed."><Components.Select.Root defaultValue="production"><Components.Select.Trigger><Components.Select.Value placeholder="Choose environment" /></Components.Select.Trigger><Components.Select.Content><Components.Select.Item value="production">Production</Components.Select.Item><Components.Select.Item value="staging">Staging</Components.Select.Item><Components.Select.Item value="development">Development</Components.Select.Item></Components.Select.Content></Components.Select.Root></Components.Field>;
    case "Switch": return <div className="docs-setting-row"><div><strong>Automatic deployment</strong><span className="cdt-muted">Promote after required checks pass</span></div><Components.Switch aria-label="Automatic deployment" defaultChecked /></div>;
    case "Checkbox": return <Components.Field label="Include prerelease versions" description="Show release candidates in component search results."><Components.Checkbox defaultChecked /></Components.Field>;
    case "Banner": return <Components.Banner tone="info" icon="i" title="Release ready" action={<Components.Button size="sm" variant="ghost">View checks</Components.Button>}>All required checks passed. You can safely promote this version.</Components.Banner>;
    case "EmptyState": return <Components.EmptyState icon="+" title="No environments yet" description="Create an environment to start deploying this project." action={<Components.Button variant="primary">Create environment</Components.Button>} />;
    case "Meter": return <div className="docs-meter"><div className="docs-meter__label"><strong>Monthly usage</strong><span className="cdt-muted">60 of 100 GB</span></div><Components.Meter aria-label="Monthly usage" value={60} valueText="60%" /></div>;
    case "ProgressRing": return <Components.ProgressRing aria-label="Example progress" value={60} valueText="60%" />;
    case "Spinner": return <Components.Spinner label="Loading" />;
    case "AppShell": return <Components.AppShell nav={<span>Navigation</span>} skipLinkLabel="Skip to preview content" style={{ minHeight: "12rem" }}>Shell content</Components.AppShell>;
    case "NavList": return <Components.NavList aria-label="Example navigation" items={[{ id: "overview", label: "Overview", href: "#overview", active: true }]} renderLink={(item, props) => <a href={item.href} {...props} />} />;
    case "TopBar": return <Components.TopBar eyebrow="Design system" title="Components" actions={<Components.IconButton aria-label="Example action" icon="●" />} />;
    default: throw new Error(`Unknown component preview: ${name}`);
  }
}

export function CatalogIndex() {
  return <section className="cdt-page" aria-labelledby="components-title"><div><p className="docs-eyebrow">Components</p><h1 id="components-title">Components</h1><p className="docs-lead">Every public @conductor-by-89soone/react component is rendered from its generated metadata.</p></div><Components.Panel as="section" aria-labelledby="framework-css-title"><h2 id="framework-css-title">Framework-agnostic CSS</h2><p className="cdt-muted">The same visual contract is available without React through public <code>cdt-*</code> classes.</p><div className="docs-preview-row"><Components.Button data-framework-example="react" variant="primary">React Button</Components.Button><button data-framework-example="css" className="cdt-btn cdt-btn--primary">CSS classes</button></div><Components.CodeBlock language="html" code={'<button class="cdt-btn cdt-btn--primary">Save</button>'} /></Components.Panel><div className="cdt-card-grid">{componentMeta.map((component) => { const titleId = `component-${component.name.toLowerCase()}`; return <Components.Panel as="section" aria-labelledby={titleId} className="docs-component-tile" key={component.name}><div className="docs-component-tile__header"><h2 id={titleId}><Link className="docs-component-link" to={`/components/${component.name}`}>{component.name}</Link></h2><span aria-hidden="true">↗</span></div><PreviewBoundary><div className="docs-preview" aria-label={`${component.name} preview`}><ComponentPreview compact name={component.name} /></div></PreviewBoundary></Components.Panel>; })}</div></section>;
}

export function ComponentDetail({ name, forceCopyUnavailable = false, forcePreviewError = false }: { readonly name: string; readonly forceCopyUnavailable?: boolean; readonly forcePreviewError?: boolean }) {
  const component = componentMeta.find((entry) => entry.name === name);
  if (component === undefined) return <Components.EmptyState title="Component not found" description={`No public component named ${name} exists.`} action={<Link to="/components">Return to components</Link>} />;
  return <section className="cdt-page" aria-labelledby="component-title"><div><p className="docs-eyebrow">Component</p><h1 id="component-title">{component.name}</h1></div><Components.Panel as="section"><h2>Live preview</h2><PreviewBoundary><div className="docs-preview"><ComponentPreview forceError={forcePreviewError} name={component.name} /></div></PreviewBoundary></Components.Panel><Components.Table caption={`${component.name} props`}><Components.Table.Head><Components.Table.Row><Components.Table.HeaderCell>Prop</Components.Table.HeaderCell><Components.Table.HeaderCell>Required</Components.Table.HeaderCell><Components.Table.HeaderCell>Type</Components.Table.HeaderCell></Components.Table.Row></Components.Table.Head><Components.Table.Body>{component.props.map((prop) => <Components.Table.Row key={prop.name}><Components.Table.Cell><code>{prop.name}</code></Components.Table.Cell><Components.Table.Cell>{prop.required ? "Yes" : "No"}</Components.Table.Cell><Components.Table.Cell><code>{prop.type}</code></Components.Table.Cell></Components.Table.Row>)}</Components.Table.Body></Components.Table><CopyCode code={`import { ${component.name} } from "@conductor-by-89soone/react";`} forceUnavailable={forceCopyUnavailable} /></section>;
}
