// Refs: WP-022 FR-DOC-006 FR-DOC-007 FR-A11Y-003 FR-QA-003
import { Banner, Button, CodeBlock, Dialog, Drawer, Field, Meter, Panel, SeverityTag, StatusBadge, Table, TextField } from "@conductor/react";
import allowList from "../../../axe-allowlist.json";
import contrastReport from "./generated/contrast-report";
import { useEffect, useState, type ReactNode } from "react";

const statusRules = [["queued", "Waiting to start"], ["running", "Work in progress"], ["waiting", "Awaiting input"], ["success", "Completed successfully"], ["partial", "Completed with exceptions"], ["danger", "Failed or unsafe"], ["neutralEnd", "Ended without a terminal result"]] as const;
const severityRules = [["read", "Read-only impact"], ["write", "Changes external state"], ["destructive", "Irreversible or destructive action"], ["blocked", "Action is prohibited"]] as const;

export function CopyCode({ code, forceUnavailable = false }: { readonly code: string; readonly forceUnavailable?: boolean }) {
  const [state, setState] = useState<"idle" | "copied" | "failed" | "unavailable">("idle");
  const available = !forceUnavailable && typeof navigator !== "undefined" && navigator.clipboard?.writeText !== undefined;
  useEffect(() => { if (state !== "copied") return undefined; const timer = window.setTimeout(() => setState("idle"), 2000); return () => window.clearTimeout(timer); }, [state]);
  const copy = async () => { if (!available) { setState("unavailable"); return; } try { await navigator.clipboard.writeText(code); setState("copied"); } catch { setState("failed"); } };
  const label = state === "copied" ? "복사됨" : state === "failed" ? "복사할 수 없음" : state === "unavailable" ? "복사할 수 없음" : "Copy code";
  return <div className="docs-code-example"><CodeBlock language="tsx" code={code} /><Button size="sm" disabled={!available} onClick={() => void copy()}>{label}</Button><span className="cdt-sr-only" aria-live="polite">{state === "copied" ? "복사됨" : ""}</span></div>;
}

function RulePair({ title, recommended, prohibited, reason }: { readonly title: string; readonly recommended: ReactNode; readonly prohibited: ReactNode; readonly reason: string }) {
  return <section className="cdt-page"><h2>{title}</h2><div className="cdt-split-layout"><Panel as="section"><h3>Recommended</h3>{recommended}</Panel><Panel as="section"><h3>Do not</h3>{prohibited}<p className="cdt-muted">Reason: {reason}</p></Panel></div></section>;
}

export function Patterns() {
  return <section className="cdt-page" aria-labelledby="patterns-title"><div><p className="docs-eyebrow">Patterns</p><h1 id="patterns-title">Patterns</h1></div><Table caption="Status usage"><Table.Head><Table.Row><Table.HeaderCell>Status</Table.HeaderCell><Table.HeaderCell>Use when</Table.HeaderCell><Table.HeaderCell>Example</Table.HeaderCell></Table.Row></Table.Head><Table.Body>{statusRules.map(([status, description]) => <Table.Row key={status}><Table.Cell>{status}</Table.Cell><Table.Cell>{description}</Table.Cell><Table.Cell><StatusBadge status={status} icon="●" label={status} /></Table.Cell></Table.Row>)}</Table.Body></Table><Table caption="Severity usage"><Table.Head><Table.Row><Table.HeaderCell>Severity</Table.HeaderCell><Table.HeaderCell>Use when</Table.HeaderCell><Table.HeaderCell>Example</Table.HeaderCell></Table.Row></Table.Head><Table.Body>{severityRules.map(([severity, description]) => <Table.Row key={severity}><Table.Cell>{severity}</Table.Cell><Table.Cell>{description}</Table.Cell><Table.Cell><SeverityTag severity={severity} icon="●" label={severity} /></Table.Cell></Table.Row>)}</Table.Body></Table><RulePair title="Status is not color alone" recommended={<StatusBadge status="success" icon="✓" label="Success" />} prohibited={<span className="docs-color-dot" aria-hidden="true" />} reason="A color-only marker is not distinguishable in grayscale or by assistive technology." /><RulePair title="Form errors need text" recommended={<Field label="Name" error="Name is required"><TextField /></Field>} prohibited={<TextField aria-label="Name" invalid />} reason="A red border alone does not communicate the error or recovery path." /><RulePair title="Exceeded meters show the value" recommended={<Meter aria-label="Usage" value={120} max={100} exceededAt={100} valueText="120% of limit" />} prohibited={<div className="docs-meter-only" aria-hidden="true" />} reason="The threshold must be conveyed with a numerical text alternative." /><Panel as="section"><h2>Density</h2><p>Use a 14px body rhythm, 1.5 line height, and controls at least 40px tall (42px on compact screens).</p></Panel><Panel as="section"><h2>Dialog or Drawer?</h2><p>Use <strong>Dialog</strong> for a focused confirmation or short task. Use <strong>Drawer</strong> for contextual detail that benefits from retaining the page alongside it.</p><div className="docs-preview-row"><Dialog.Root><Dialog.Trigger>Open dialog example</Dialog.Trigger><Dialog.Content><Dialog.Title>Confirm action</Dialog.Title><Dialog.Description>Use a Dialog for a focused decision.</Dialog.Description></Dialog.Content></Dialog.Root><Drawer.Root><Drawer.Trigger>Open drawer example</Drawer.Trigger><Drawer.Content><Drawer.Title>Contextual detail</Drawer.Title></Drawer.Content></Drawer.Root></div></Panel><Panel as="section">No separate rules are published for layout-only and decorative primitives; they are intentionally omitted.</Panel></section>;
}

const axeAllowList = allowList as readonly { readonly rule: string; readonly reason: string }[];

export function Accessibility() {
  const report = contrastReport as { readonly summary?: { readonly passed: number; readonly failed: number; readonly checks: number } } | null;
  return <section className="cdt-page" aria-labelledby="accessibility-title"><div><p className="docs-eyebrow">Accessibility</p><h1 id="accessibility-title">Accessibility</h1><p className="docs-lead">Conductor targets WCAG 2.1 AA and delegates complex overlay behavior to Radix primitives.</p></div><Panel as="section"><h2>Contrast report</h2>{report === null ? <Banner tone="warning">Contrast metrics are unavailable.</Banner> : <p>{report.summary?.passed} of {report.summary?.checks} checks passed; {report.summary?.failed} failed.</p>}<p>Focus rings and control borders are checked as non-text at 3:1 or better.</p></Panel><Panel as="section"><h2>Keyboard paths</h2><ul><li>Tab follows visual order and the skip link reaches main content.</li><li>Escape closes Dialog, Drawer, DropdownMenu, and Select.</li><li>Focus returns to the trigger after an overlay closes.</li></ul></Panel><Panel as="section"><h2>axe allow list</h2>{axeAllowList.length === 0 ? <p>No axe exceptions are currently allowed.</p> : <Table caption="axe allow list"><Table.Head><Table.Row><Table.HeaderCell>Rule</Table.HeaderCell><Table.HeaderCell>Reason</Table.HeaderCell></Table.Row></Table.Head><Table.Body>{axeAllowList.map((entry) => <Table.Row key={entry.rule}><Table.Cell>{entry.rule}</Table.Cell><Table.Cell>{entry.reason}</Table.Cell></Table.Row>)}</Table.Body></Table>}</Panel><Panel as="section"><h2>Color is not the only signal</h2><p>Status, severity, invalid fields, and exceeded meters expose text and/or icons in addition to color.</p></Panel></section>;
}
